package practica2parking;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author David
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PantallaReciboImprimirse = new javax.swing.JDialog();
        CargaImprimir = new javax.swing.JProgressBar();
        ReciboImprimiendose = new javax.swing.JLabel();
        VolverPrincipal1 = new javax.swing.JButton();
        AñadirCoche = new javax.swing.JDialog();
        SacarCoche = new javax.swing.JDialog();
        TituloPrincipal = new javax.swing.JLabel();
        NuevoCoche = new javax.swing.JButton();
        EliminarCoche = new javax.swing.JButton();
        ImprimirRecibo = new javax.swing.JButton();

        PantallaReciboImprimirse.setMaximumSize(new java.awt.Dimension(500, 300));
        PantallaReciboImprimirse.setMinimumSize(new java.awt.Dimension(500, 300));
        PantallaReciboImprimirse.setPreferredSize(new java.awt.Dimension(500, 300));
        PantallaReciboImprimirse.setType(java.awt.Window.Type.POPUP);

        CargaImprimir.setStringPainted(true);

        ReciboImprimiendose.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ReciboImprimiendose.setText("Recibo Imprimiendose...");
        ReciboImprimiendose.setMaximumSize(new java.awt.Dimension(200, 50));
        ReciboImprimiendose.setMinimumSize(new java.awt.Dimension(200, 50));
        ReciboImprimiendose.setPreferredSize(new java.awt.Dimension(200, 50));

        VolverPrincipal1.setText("Aceptar");
        VolverPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverPrincipal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PantallaReciboImprimirseLayout = new javax.swing.GroupLayout(PantallaReciboImprimirse.getContentPane());
        PantallaReciboImprimirse.getContentPane().setLayout(PantallaReciboImprimirseLayout);
        PantallaReciboImprimirseLayout.setHorizontalGroup(
            PantallaReciboImprimirseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaReciboImprimirseLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(CargaImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addGroup(PantallaReciboImprimirseLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(ReciboImprimiendose, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PantallaReciboImprimirseLayout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(VolverPrincipal1)
                .addGap(225, 225, 225))
        );
        PantallaReciboImprimirseLayout.setVerticalGroup(
            PantallaReciboImprimirseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PantallaReciboImprimirseLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(ReciboImprimiendose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(CargaImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(VolverPrincipal1)
                .addGap(50, 50, 50))
        );

        PantallaReciboImprimirse.getAccessibleContext().setAccessibleParent(ImprimirRecibo);

        javax.swing.GroupLayout AñadirCocheLayout = new javax.swing.GroupLayout(AñadirCoche.getContentPane());
        AñadirCoche.getContentPane().setLayout(AñadirCocheLayout);
        AñadirCocheLayout.setHorizontalGroup(
            AñadirCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        AñadirCocheLayout.setVerticalGroup(
            AñadirCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SacarCocheLayout = new javax.swing.GroupLayout(SacarCoche.getContentPane());
        SacarCoche.getContentPane().setLayout(SacarCocheLayout);
        SacarCocheLayout.setHorizontalGroup(
            SacarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SacarCocheLayout.setVerticalGroup(
            SacarCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setName("Principal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));

        TituloPrincipal.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        TituloPrincipal.setText("Bienvenido al Servicio de Parking");
        TituloPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NuevoCoche.setText("Añadir coche al parking");
        NuevoCoche.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NuevoCoche.setMaximumSize(new java.awt.Dimension(155, 25));
        NuevoCoche.setMinimumSize(new java.awt.Dimension(155, 25));
        NuevoCoche.setPreferredSize(new java.awt.Dimension(155, 25));

        EliminarCoche.setText("Sacar coche del parking");
        EliminarCoche.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EliminarCoche.setMaximumSize(new java.awt.Dimension(155, 25));
        EliminarCoche.setMinimumSize(new java.awt.Dimension(155, 25));
        EliminarCoche.setPreferredSize(new java.awt.Dimension(155, 25));

        ImprimirRecibo.setText("Imprimir Recibo");
        ImprimirRecibo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImprimirReciboMouseClicked(evt);
            }
        });
        ImprimirRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirReciboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(NuevoCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(EliminarCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(TituloPrincipal)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ImprimirRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(TituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NuevoCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(ImprimirRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImprimirReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirReciboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImprimirReciboActionPerformed

    private void VolverPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverPrincipal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolverPrincipal1ActionPerformed

    private void ImprimirReciboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImprimirReciboMouseClicked
        // TODO add your handling code here:
        //Escribir aqui metodo para que aparezca el popup de imprimirecibo
    }//GEN-LAST:event_ImprimirReciboMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AñadirCoche;
    private javax.swing.JProgressBar CargaImprimir;
    private javax.swing.JButton EliminarCoche;
    private javax.swing.JButton ImprimirRecibo;
    private javax.swing.JButton NuevoCoche;
    private javax.swing.JDialog PantallaReciboImprimirse;
    private javax.swing.JLabel ReciboImprimiendose;
    private javax.swing.JDialog SacarCoche;
    private javax.swing.JLabel TituloPrincipal;
    private javax.swing.JButton VolverPrincipal1;
    // End of variables declaration//GEN-END:variables
}
