/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package intento2Parking;

import java.util.ArrayList;

/**
 *
 * @author David
 */
public class SacarCoches extends javax.swing.JDialog {
    private  ArrayList<String> DineroIntroducido = new ArrayList<>();
    private  ArrayList<String> CantidadDineros = new ArrayList<>();
    private Maquina maquina;
    private Ticket ticket;
    /**
     * Creates new form MeterCoche
     */
    public SacarCoches(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DineroIntroducir();
        CantidadDinero();
    }
    private void DineroIntroducir() {
    String[] dinero = {"20","10","5","2","1","0.5","0.2","0.1"}; 
}
     private void CantidadDinero() {
    String[] cantidades = {"1","2","3","4","5","6","7","8","9","10"}; 
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DineroIntroducir = new javax.swing.JComboBox<>();
        CantidadDinero = new javax.swing.JComboBox<>();
        SeleccioneDineroMeter = new javax.swing.JLabel();
        AceptarDineroMetido = new javax.swing.JButton();
        Dinero = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PrecioEstancia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        DineroIntroducir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20 €", "10 €", "5 €", "2 €", "1 €", "0.5 €", "0.2 €", "0.1 €" }));
        DineroIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DineroIntroducirActionPerformed(evt);
            }
        });

        CantidadDinero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        SeleccioneDineroMeter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SeleccioneDineroMeter.setText("Seleccione la cantidad de dinero a meter:");

        AceptarDineroMetido.setText("Continuar");
        AceptarDineroMetido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AceptarDineroMetidoMouseClicked(evt);
            }
        });
        AceptarDineroMetido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarDineroMetidoActionPerformed(evt);
            }
        });

        Dinero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Dinero.setText("Dinero:");

        Cantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cantidad.setText("Cantidad:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Total a pagar: ");

        PrecioEstancia.setEditable(false);
        PrecioEstancia.setText(Dinero.toString());
        PrecioEstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioEstanciaActionPerformed(evt);
            }
        });

        jButton1.setText("Pagar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(SeleccioneDineroMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(PrecioEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AceptarDineroMetido)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DineroIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantidadDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioEstancia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SeleccioneDineroMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DineroIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantidadDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarDineroMetido)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DineroIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DineroIntroducirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DineroIntroducirActionPerformed

    private void AceptarDineroMetidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarDineroMetidoMouseClicked
        // TODO add your handling code here:                                              
        String seleccionado = (String) DineroIntroducir.getSelectedItem();
        DineroIntroducido.add(seleccionado); 
        
        String seleccionado2 = (String) CantidadDinero.getSelectedItem();
        CantidadDineros.add(seleccionado2); 
        
    }//GEN-LAST:event_AceptarDineroMetidoMouseClicked

    private void PrecioEstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioEstanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioEstanciaActionPerformed

    private void AceptarDineroMetidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarDineroMetidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarDineroMetidoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       maquina.pagarYSalir(this.ticket, CENTER_ALIGNMENT);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SacarCoches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SacarCoches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SacarCoches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SacarCoches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SacarCoches dialog = new SacarCoches(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarDineroMetido;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JComboBox<String> CantidadDinero;
    private javax.swing.JLabel Dinero;
    private javax.swing.JComboBox<String> DineroIntroducir;
    private javax.swing.JTextField PrecioEstancia;
    private javax.swing.JLabel SeleccioneDineroMeter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
