/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package intento2Parking;

import javax.swing.JOptionPane;

/**
 *
 * @author David
 */

public class MeterCoches extends javax.swing.JDialog {

    private static Maquina maquina;
    private static Ticket ticket;
    private static Parking parking;

    /**
     * Creates new form SacarCoche
     *
     * @param parent
     * @param modal
     */
    public MeterCoches(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        String matricula ="";
        int piso=0;
        int plaza=0;
        
         if (maquina == null) {
        maquina = new Maquina(0.5);
    }
    if (ticket == null) {
        ticket = new Ticket(matricula, piso, plaza);
    }
    if (parking == null) {
        parking = new Parking();
    }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MeterCocheConfirmar = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        IntroducirMatricula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        MeterCocheConfirmar.setText("Meter nuevo coche");
        MeterCocheConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MeterCocheConfirmarMouseClicked(evt);
            }
        });
        MeterCocheConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeterCocheConfirmarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intento2Parking/Recursos/istockphoto-1268257891-612x612.png"))); // NOI18N

        IntroducirMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IntroducirMatriculaMouseClicked(evt);
            }
        });
        IntroducirMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntroducirMatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(MeterCocheConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(IntroducirMatricula))
                            .addComponent(jLabel4))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IntroducirMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(MeterCocheConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MeterCocheConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeterCocheConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MeterCocheConfirmarActionPerformed

    private void IntroducirMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntroducirMatriculaActionPerformed

    }//GEN-LAST:event_IntroducirMatriculaActionPerformed

    private void MeterCocheConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MeterCocheConfirmarMouseClicked
        String matricula = IntroducirMatricula.getText().trim(); // Obtener la matrícula ingresada

    if (matricula.isEmpty()) {  // Comprobar que no esté vacía
        JOptionPane.showMessageDialog(this, "Por favor, introduce una matrícula antes de continuar", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Intentamos estacionar el coche
        Ticket resultado = maquina.generarTicket(matricula);

        if (resultado == null) {
            JOptionPane.showMessageDialog(this, "Parking lleno, inténtelo de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            //Mostramos ticket
            JOptionPane.showMessageDialog(this, resultado.toString(), 
                                          "Éxito", JOptionPane.INFORMATION_MESSAGE);
            dispose(); // Cerrar ventana si todo está correcto
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al procesar la operación", "Error", JOptionPane.ERROR_MESSAGE);
    }
    


    }//GEN-LAST:event_MeterCocheConfirmarMouseClicked

    private void IntroducirMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IntroducirMatriculaMouseClicked
       
    }//GEN-LAST:event_IntroducirMatriculaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(MeterCoches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(MeterCoches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(MeterCoches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(MeterCoches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            MeterCoches dialog = new MeterCoches(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IntroducirMatricula;
    private javax.swing.JToggleButton MeterCocheConfirmar;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
