/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package intento2Parking;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class SacarCoches extends javax.swing.JDialog {
    private final  ArrayList<String> DineroIntroducido = new ArrayList<>();
    private final  ArrayList<String> CantidadDineros = new ArrayList<>();
    private Maquina maquina;
    private Ticket ticket;
    private Parking parking;
    private static DepositoDinero dineros;
    /**
     * Creates new form MeterCoche
     * @param parent
     * @param modal
     */
    public SacarCoches(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        DineroIntroducir();
        CantidadDinero();
    }
    public void MostrarCostoTotal() { //Sirve para mostrar el precio total a pagar del coche
    double dinero = maquina.calcularTarifa(ticket);  
    PrecioEstancia.setText(String.valueOf(dinero)); 
    }
    private void DineroIntroducir() { //Metodos modelo para sacar el valor introducida en el Jcombobox
        double [] ValoresModelo = {20, 10, 5, 2, 1, 0.5, 0.2, 0.1, 0.05};
}
     private void CantidadDinero() { //Metodos modelo para sacar la cantidad introducida en el Jcombobox
        double[] cantidadesmodelo = {1,2,3,4,5,6,7,8,9};
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DineroIntroducir = new javax.swing.JComboBox<>();
        CantidadDinero = new javax.swing.JComboBox<>();
        SeleccioneDineroMeter = new javax.swing.JLabel();
        AceptarDineroMetido = new javax.swing.JButton();
        Dinero = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PrecioEstancia = new javax.swing.JTextField();
        Pagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        DineroIntroducir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20 €", "10 €", "5 €", "2 €", "1 €", "0.5 €", "0.2 €", "0.1 €" }));
        DineroIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DineroIntroducirActionPerformed(evt);
            }
        });

        CantidadDinero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        SeleccioneDineroMeter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SeleccioneDineroMeter.setText("Seleccione la cantidad de dinero a meter:");

        AceptarDineroMetido.setText("Continuar");
        AceptarDineroMetido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AceptarDineroMetidoMouseClicked(evt);
            }
        });
        AceptarDineroMetido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarDineroMetidoActionPerformed(evt);
            }
        });

        Dinero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Dinero.setText("Dinero:");

        Cantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cantidad.setText("Cantidad:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Total a pagar: ");

        PrecioEstancia.setEditable(false);
        PrecioEstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioEstanciaActionPerformed(evt);
            }
        });

        Pagar.setText("Pagar");
        Pagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PagarMouseClicked(evt);
            }
        });
        Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AceptarDineroMetido)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addComponent(DineroIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantidadDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pagar))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PrecioEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(SeleccioneDineroMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioEstancia, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(SeleccioneDineroMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DineroIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantidadDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarDineroMetido)
                    .addComponent(Pagar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DineroIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DineroIntroducirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DineroIntroducirActionPerformed

    private void AceptarDineroMetidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarDineroMetidoMouseClicked
        // TODO add your handling code here:  
        /*Con las clases modelo DineroIntroducir y CantidadDinero, comparamos el valor seleccionado en el Jcombobox
        y sacamos esta informacion al metodo DineroIntroducido y CantidadDineros */
        String seleccionado = (String) DineroIntroducir.getSelectedItem();
        DineroIntroducido.add(seleccionado); 
        
        String seleccionado2 = (String) CantidadDinero.getSelectedItem();
        CantidadDineros.add(seleccionado2); 
        
    }//GEN-LAST:event_AceptarDineroMetidoMouseClicked

    private void PrecioEstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioEstanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioEstanciaActionPerformed

    private void AceptarDineroMetidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarDineroMetidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarDineroMetidoActionPerformed

    private void PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PagarActionPerformed

    private void PagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PagarMouseClicked
        try{ //Se encarga de verificar que no intentas sacar un coche si el parking esta vacio, ergo, si no existe ningun ticket
        parking.vaciarPlaza(ticket);
        dispose();
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(this, "No existe ningun coche en el parking", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_PagarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SacarCoches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SacarCoches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SacarCoches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SacarCoches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SacarCoches dialog = new SacarCoches(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarDineroMetido;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JComboBox<String> CantidadDinero;
    private javax.swing.JLabel Dinero;
    private javax.swing.JComboBox<String> DineroIntroducir;
    private javax.swing.JButton Pagar;
    private javax.swing.JTextField PrecioEstancia;
    private javax.swing.JLabel SeleccioneDineroMeter;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
