/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intento2Parking;

/**
 *
 * @author David
 */
public class Terminal extends javax.swing.JFrame {

    /**
     * Creates new form Terminal
     */
    public Terminal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloTerminal = new javax.swing.JLabel();
        BotonMeterCoche = new javax.swing.JButton();
        SacarCoche = new javax.swing.JButton();
        IconoCocheTerminal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloTerminal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TituloTerminal.setText("Seleccione que desea hacer:");

        BotonMeterCoche.setText("Añadir nuevo coche");
        BotonMeterCoche.setMaximumSize(new java.awt.Dimension(300, 100));
        BotonMeterCoche.setMinimumSize(new java.awt.Dimension(300, 100));
        BotonMeterCoche.setPreferredSize(new java.awt.Dimension(300, 100));
        BotonMeterCoche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMeterCocheMouseClicked(evt);
            }
        });
        BotonMeterCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMeterCocheActionPerformed(evt);
            }
        });

        SacarCoche.setText("Sacar nuevo coche");
        SacarCoche.setMaximumSize(new java.awt.Dimension(300, 100));
        SacarCoche.setMinimumSize(new java.awt.Dimension(300, 100));
        SacarCoche.setPreferredSize(new java.awt.Dimension(300, 100));
        SacarCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SacarCocheActionPerformed(evt);
            }
        });

        IconoCocheTerminal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intento2Parking/Recursos/CocheIcono.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonMeterCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SacarCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(TituloTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(IconoCocheTerminal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(TituloTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IconoCocheTerminal)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonMeterCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SacarCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMeterCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMeterCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMeterCocheActionPerformed

    private void BotonMeterCocheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMeterCocheMouseClicked
        // TODO add your handling code here:
        //Hace visible el Jframe para introducir un coche nuevo
        MeterCoches metercoche = new MeterCoches(this, true);
        metercoche.setVisible(true);
    }//GEN-LAST:event_BotonMeterCocheMouseClicked

    private void SacarCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SacarCocheActionPerformed
        // TODO add your handling code here:
        //Hace visible el Jframe para sacar un coche del parking
        ComprobarMatriculaPago comprobarmatri = new ComprobarMatriculaPago ();
        comprobarmatri.setVisible(true);
    }//GEN-LAST:event_SacarCocheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMeterCoche;
    private javax.swing.JLabel IconoCocheTerminal;
    private javax.swing.JButton SacarCoche;
    private javax.swing.JLabel TituloTerminal;
    // End of variables declaration//GEN-END:variables
}
